/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author LENOVO
 */
public class CHOOSEUSER extends javax.swing.JFrame {

    /**
     * Creates new form CHOOSEUSER
     */
    public CHOOSEUSER() {
        initComponents();
        MINISTATEMENTBTN2.setVisible(false);
        INFORMATIONSBTN2.setVisible(false);
        BACKBTN2.setVisible(false);
        combouser.addItem(null);
        comboemployee.addItem(null);
        setcomboemployee();
        setcombouser();
    }
    int MYACC,qr;
    public CHOOSEUSER(int n1,int n2) {
        
        MYACC=n1;
        qr=n2;
        if(qr!=1)
        {
            JOptionPane.showMessageDialog(null, " This Page Has A Specific Informations Only Employees Can See It ");
            new MainMenu(MYACC,qr).setVisible(true);
            this.dispose();
        }
        else
        {
        initComponents();
        MINISTATEMENTBTN2.setVisible(false);
        INFORMATIONSBTN2.setVisible(false);
        BACKBTN2.setVisible(false);
        combouser.addItem(null);
        comboemployee.addItem(null);
        setcomboemployee();
        setcombouser(); 
        }
    }
    
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EXITBTN = new javax.swing.JButton();
        comboemployee = new javax.swing.JComboBox<>();
        canvas1 = new java.awt.Canvas();
        jPanel3 = new javax.swing.JPanel();
        MINISTATEMENTBTN1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        combouser = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        INFORMATIONSBTN1 = new javax.swing.JButton();
        BACKBTN1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        MINISTATEMENTBTN2 = new javax.swing.JButton();
        INFORMATIONSBTN2 = new javax.swing.JButton();
        BACKBTN2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ATM MANAGMENT SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 730, 44));

        EXITBTN.setBackground(new java.awt.Color(102, 0, 102));
        EXITBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EXITBTN.setForeground(new java.awt.Color(255, 255, 255));
        EXITBTN.setText("X");
        EXITBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EXITBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITBTNMouseClicked(evt);
            }
        });
        jPanel2.add(EXITBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 110));

        comboemployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboemployee.setForeground(new java.awt.Color(102, 0, 102));
        comboemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(comboemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 207, -1));
        jPanel1.add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 835, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 742, -1, -1));

        MINISTATEMENTBTN1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MINISTATEMENTBTN1.setForeground(new java.awt.Color(102, 0, 102));
        MINISTATEMENTBTN1.setText("SHOW ALL MINISTATEMENT");
        MINISTATEMENTBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINISTATEMENTBTN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MINISTATEMENTBTN1MouseEntered(evt);
            }
        });
        MINISTATEMENTBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINISTATEMENTBTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(MINISTATEMENTBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 280, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("List Of All Employees");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 227, 44));

        combouser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combouser.setForeground(new java.awt.Color(102, 0, 102));
        combouser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 207, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("List Of All Users");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 203, 207, 44));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("GET INFORMATIONS");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 130, 730, 44));

        INFORMATIONSBTN1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        INFORMATIONSBTN1.setForeground(new java.awt.Color(102, 0, 102));
        INFORMATIONSBTN1.setText("SHOW ALL INFORMATIONS");
        INFORMATIONSBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INFORMATIONSBTN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                INFORMATIONSBTN1MouseEntered(evt);
            }
        });
        INFORMATIONSBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMATIONSBTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(INFORMATIONSBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 280, -1));

        BACKBTN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BACKBTN1.setForeground(new java.awt.Color(153, 0, 153));
        BACKBTN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BACKBTN1.setText("Back");
        BACKBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKBTN1MouseEntered(evt);
            }
        });
        jPanel1.add(BACKBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 730, 44));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BANK OF EGYPT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 730, 44));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\go.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 730, 330));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 730, -1));

        MINISTATEMENTBTN2.setBackground(new java.awt.Color(102, 0, 102));
        MINISTATEMENTBTN2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MINISTATEMENTBTN2.setForeground(new java.awt.Color(255, 255, 255));
        MINISTATEMENTBTN2.setText("SHOW ALL MINISTATEMENT");
        MINISTATEMENTBTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MINISTATEMENTBTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINISTATEMENTBTN2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MINISTATEMENTBTN2MouseExited(evt);
            }
        });
        MINISTATEMENTBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINISTATEMENTBTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(MINISTATEMENTBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 280, -1));

        INFORMATIONSBTN2.setBackground(new java.awt.Color(102, 0, 102));
        INFORMATIONSBTN2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        INFORMATIONSBTN2.setForeground(new java.awt.Color(255, 255, 255));
        INFORMATIONSBTN2.setText("SHOW ALL INFORMATIONS");
        INFORMATIONSBTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INFORMATIONSBTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INFORMATIONSBTN2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                INFORMATIONSBTN2MouseExited(evt);
            }
        });
        INFORMATIONSBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMATIONSBTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(INFORMATIONSBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 280, -1));

        BACKBTN2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BACKBTN2.setForeground(new java.awt.Color(102, 0, 102));
        BACKBTN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BACKBTN2.setText("Back");
        BACKBTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACKBTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKBTN2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKBTN2MouseExited(evt);
            }
        });
        jPanel1.add(BACKBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 730, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MINISTATEMENTBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINISTATEMENTBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MINISTATEMENTBTN1ActionPerformed

    private void MINISTATEMENTBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINISTATEMENTBTN1MouseClicked

    }//GEN-LAST:event_MINISTATEMENTBTN1MouseClicked

    private void EXITBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITBTNMouseClicked
        System.exit(1);
    }//GEN-LAST:event_EXITBTNMouseClicked

    private void INFORMATIONSBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFORMATIONSBTN1MouseClicked
        if(combouser.getSelectedItem()!=null &&comboemployee.getSelectedItem()!=null){
            JOptionPane.showMessageDialog(null, " You Can't Select Both (: ");
        }
        else if(combouser.getSelectedItem()==null &&comboemployee.getSelectedItem()==null){
             JOptionPane.showMessageDialog(null, " You Should Select One At Least (: ");
        }
        else if(combouser.getSelectedItem()==null &&comboemployee.getSelectedItem()!=null){
            getnumforemployee();
            new INFORMATIONS(Integer.valueOf(MYACCNUM),1,MYACC,qr).setVisible(true);
            this.dispose();
        }
        else if(combouser.getSelectedItem()!=null &&comboemployee.getSelectedItem()==null){
            getnumforuser();
            new INFORMATIONS(Integer.valueOf(MYACCNUM),2,MYACC,qr).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_INFORMATIONSBTN1MouseClicked

    private void INFORMATIONSBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMATIONSBTN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INFORMATIONSBTN1ActionPerformed

    private void INFORMATIONSBTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFORMATIONSBTN2MouseClicked
        if(combouser.getSelectedItem()!=null &&comboemployee.getSelectedItem()!=null){
            JOptionPane.showMessageDialog(null, " You Can't Select Both (: ");
        }
        else if(combouser.getSelectedItem()==null &&comboemployee.getSelectedItem()==null){
             JOptionPane.showMessageDialog(null, " You Should Select One At Least (: ");
        }
        else if(combouser.getSelectedItem()==null &&comboemployee.getSelectedItem()!=null){
            getnumforemployee();
            new INFORMATIONS(Integer.valueOf(MYACCNUM),1,MYACC,qr).setVisible(true);
            this.dispose();
        }
        else if(combouser.getSelectedItem()!=null &&comboemployee.getSelectedItem()==null){
            getnumforuser();
            new INFORMATIONS(Integer.valueOf(MYACCNUM),2,MYACC,qr).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_INFORMATIONSBTN2MouseClicked

    private void INFORMATIONSBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMATIONSBTN2ActionPerformed
       
    }//GEN-LAST:event_INFORMATIONSBTN2ActionPerformed

    private void INFORMATIONSBTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFORMATIONSBTN1MouseEntered
        INFORMATIONSBTN1.setVisible(false);
         INFORMATIONSBTN2.setVisible(true);
    }//GEN-LAST:event_INFORMATIONSBTN1MouseEntered

    private void INFORMATIONSBTN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFORMATIONSBTN2MouseExited
         INFORMATIONSBTN1.setVisible(true);
         INFORMATIONSBTN2.setVisible(false);
    }//GEN-LAST:event_INFORMATIONSBTN2MouseExited

    private void MINISTATEMENTBTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINISTATEMENTBTN1MouseEntered
         MINISTATEMENTBTN1.setVisible(false);
         MINISTATEMENTBTN2.setVisible(true);
    }//GEN-LAST:event_MINISTATEMENTBTN1MouseEntered

    private void MINISTATEMENTBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINISTATEMENTBTN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MINISTATEMENTBTN2ActionPerformed

    private void MINISTATEMENTBTN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINISTATEMENTBTN2MouseExited
        MINISTATEMENTBTN1.setVisible(true);
        MINISTATEMENTBTN2.setVisible(false);
    }//GEN-LAST:event_MINISTATEMENTBTN2MouseExited
    String MYACCNUM;
    private void MINISTATEMENTBTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINISTATEMENTBTN2MouseClicked
        if(combouser.getSelectedItem()!=null &&comboemployee.getSelectedItem()!=null){
            JOptionPane.showMessageDialog(null, " You Can't Select Both (: ");
        }
        else if(combouser.getSelectedItem()==null &&comboemployee.getSelectedItem()==null){
             JOptionPane.showMessageDialog(null, " You Should Select One At Least (: ");
        }
        else if(combouser.getSelectedItem()==null &&comboemployee.getSelectedItem()!=null){
            getnumforemployee();
            new MINISTATMENT(Integer.valueOf(MYACCNUM),1,MYACC,qr).setVisible(true);
            this.dispose();
        }
        else if(combouser.getSelectedItem()!=null &&comboemployee.getSelectedItem()==null){
            getnumforuser();
            new MINISTATMENT(Integer.valueOf(MYACCNUM),2,MYACC,qr).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_MINISTATEMENTBTN2MouseClicked

    private void BACKBTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN1MouseEntered
        BACKBTN1.setVisible(false);
        BACKBTN2.setVisible(true);
    }//GEN-LAST:event_BACKBTN1MouseEntered

    private void BACKBTN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN2MouseExited
        BACKBTN1.setVisible(true);
        BACKBTN2.setVisible(false);
    }//GEN-LAST:event_BACKBTN2MouseExited

    private void BACKBTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN2MouseClicked
        new MainMenu(MYACC,qr).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACKBTN2MouseClicked
    Connection con =null ;
    PreparedStatement pst = null;
    ResultSet Rs=null;
    Statement st;
    public void setcombouser(){
         con =null ;
         pst = null;
         Rs=null;
         st=null;
          try{
                String query="SELECT AccName FROM accounttbl";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                Rs=pst.executeQuery();
                if( Rs.next())
                {
                    String n=Rs.getString("AccName"); 
                    combouser.addItem(n);
                    while(Rs.next())
                    {
                        //JOptionPane.showMessageDialog(null, " PIN Updated Successfuly (: ");
                         n=Rs.getString("AccName"); 
                        combouser.addItem(n);
                    }
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "No Users In The System ): ");
                }
                con.close();
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
    }
    public void setcomboemployee(){
         con =null ;
         pst = null;
         Rs=null;
         st=null;
          try{
                    String query="SELECT name FROM employee";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                    pst = con.prepareStatement(query);
                    Rs=pst.executeQuery();
                    if( Rs.next())
                    {
                         String n=Rs.getString("name"); 
                         comboemployee.addItem(n);
                        while(Rs.next()){
                            //JOptionPane.showMessageDialog(null, " PIN Updated Successfuly (: ");
                             n=Rs.getString("name"); 
                            comboemployee.addItem(n);
                        }
                    }
                    else
                    {
                         JOptionPane.showMessageDialog(null, "No Users In The System ): ");
                    }
                    con.close();
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
    }
    public void getnumforuser(){
         con =null ;
         pst = null;
         Rs=null;
         st=null;
         String query=" select * from accounttbl where AccName = ? ";
         try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                pst.setString(1, combouser.getSelectedItem().toString());
                Rs = pst.executeQuery();
                if(Rs.next())
                {
                    String x=Rs.getString("AccNum");
                    MYACCNUM=x;
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                    
    }
    public void getnumforemployee(){
         con =null ;
         pst = null;
         Rs=null;
         st=null;
         String query=" select * from employee where name = ? ";
         try{ 
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                pst.setString(1, comboemployee.getSelectedItem().toString());
                Rs = pst.executeQuery();
                if(Rs.next())
                {
                    String x=Rs.getString("accnum");
                    MYACCNUM=x;
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHOOSEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHOOSEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHOOSEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHOOSEUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHOOSEUSER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKBTN1;
    private javax.swing.JLabel BACKBTN2;
    private javax.swing.JButton EXITBTN;
    private javax.swing.JButton INFORMATIONSBTN1;
    private javax.swing.JButton INFORMATIONSBTN2;
    private javax.swing.JButton MINISTATEMENTBTN1;
    private javax.swing.JButton MINISTATEMENTBTN2;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> comboemployee;
    private javax.swing.JComboBox<String> combouser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
