/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;

/**
 *
 * @author LENOVO
 */
public class CHOOSESERVICE extends javax.swing.JFrame {

    /**
     * Creates new form CHOOSESERVICE
     */
    public CHOOSESERVICE() {
        initComponents();
        BACKBTN2.setVisible(false);
        LOGUSERBTN1.setVisible(false);
        SIGNUPUSERBTN1.setVisible(false);
        LOGINEMPLOYEEBTN1.setVisible(false);
        SIGNUPEMPLOYEEBTN1.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LOGUSERBTN = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        BACKBTN1 = new javax.swing.JButton();
        SIGNUPUSERBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LOGINEMPLOYEEBTN = new javax.swing.JButton();
        SIGNUPEMPLOYEEBTN = new javax.swing.JButton();
        BACKBTN2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LOGUSERBTN1 = new javax.swing.JButton();
        SIGNUPUSERBTN1 = new javax.swing.JButton();
        LOGINEMPLOYEEBTN1 = new javax.swing.JButton();
        SIGNUPEMPLOYEEBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 0, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BANK OF EGYPT");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 44));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 90));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("CHOOSE SERVICE");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 127, -1, -1));

        LOGUSERBTN.setBackground(new java.awt.Color(102, 0, 102));
        LOGUSERBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LOGUSERBTN.setForeground(new java.awt.Color(255, 255, 255));
        LOGUSERBTN.setText("LOG IN AS A USER");
        LOGUSERBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGUSERBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGUSERBTNMouseEntered(evt);
            }
        });
        LOGUSERBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGUSERBTNActionPerformed(evt);
            }
        });
        jPanel5.add(LOGUSERBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 530, 52));

        jPanel7.setBackground(new java.awt.Color(102, 0, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 567, 524, -1));

        BACKBTN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BACKBTN1.setForeground(new java.awt.Color(102, 0, 102));
        BACKBTN1.setText("EXIT");
        BACKBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKBTN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKBTN1MouseEntered(evt);
            }
        });
        jPanel5.add(BACKBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 453, 150, 52));

        SIGNUPUSERBTN.setBackground(new java.awt.Color(102, 0, 102));
        SIGNUPUSERBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SIGNUPUSERBTN.setForeground(new java.awt.Color(255, 255, 255));
        SIGNUPUSERBTN.setText("SIGN UP AS A USER");
        SIGNUPUSERBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGNUPUSERBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SIGNUPUSERBTNMouseEntered(evt);
            }
        });
        jPanel5.add(SIGNUPUSERBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 247, 530, 52));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BANK OF EGYPT");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 530, 44));

        LOGINEMPLOYEEBTN.setBackground(new java.awt.Color(102, 0, 102));
        LOGINEMPLOYEEBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LOGINEMPLOYEEBTN.setForeground(new java.awt.Color(255, 255, 255));
        LOGINEMPLOYEEBTN.setText("LOG IN AS AN EMPLOYEE");
        LOGINEMPLOYEEBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINEMPLOYEEBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LOGINEMPLOYEEBTNMouseEntered(evt);
            }
        });
        jPanel5.add(LOGINEMPLOYEEBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 530, 52));

        SIGNUPEMPLOYEEBTN.setBackground(new java.awt.Color(102, 0, 102));
        SIGNUPEMPLOYEEBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SIGNUPEMPLOYEEBTN.setForeground(new java.awt.Color(255, 255, 255));
        SIGNUPEMPLOYEEBTN.setText("SIGN UP AS AN EMPLOYEE");
        SIGNUPEMPLOYEEBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGNUPEMPLOYEEBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SIGNUPEMPLOYEEBTNMouseEntered(evt);
            }
        });
        jPanel5.add(SIGNUPEMPLOYEEBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 383, 530, 52));

        BACKBTN2.setBackground(new java.awt.Color(102, 0, 102));
        BACKBTN2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BACKBTN2.setForeground(new java.awt.Color(255, 255, 255));
        BACKBTN2.setText("EXIT");
        BACKBTN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACKBTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKBTN2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKBTN2MouseExited(evt);
            }
        });
        jPanel5.add(BACKBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 453, 150, 52));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 530, 10));

        LOGUSERBTN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LOGUSERBTN1.setForeground(new java.awt.Color(102, 0, 102));
        LOGUSERBTN1.setText("LOG IN AS A USER");
        LOGUSERBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGUSERBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGUSERBTN1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGUSERBTN1MouseExited(evt);
            }
        });
        jPanel5.add(LOGUSERBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 177, 530, 52));

        SIGNUPUSERBTN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SIGNUPUSERBTN1.setForeground(new java.awt.Color(102, 0, 102));
        SIGNUPUSERBTN1.setText("SIGN UP AS A USER");
        SIGNUPUSERBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SIGNUPUSERBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGNUPUSERBTN1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SIGNUPUSERBTN1MouseExited(evt);
            }
        });
        jPanel5.add(SIGNUPUSERBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 247, 530, 52));

        LOGINEMPLOYEEBTN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LOGINEMPLOYEEBTN1.setForeground(new java.awt.Color(102, 0, 102));
        LOGINEMPLOYEEBTN1.setText("LOG IN AS AN EMPLOYEE");
        LOGINEMPLOYEEBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGINEMPLOYEEBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINEMPLOYEEBTN1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LOGINEMPLOYEEBTN1MouseExited(evt);
            }
        });
        jPanel5.add(LOGINEMPLOYEEBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 530, 52));

        SIGNUPEMPLOYEEBTN1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SIGNUPEMPLOYEEBTN1.setForeground(new java.awt.Color(102, 0, 102));
        SIGNUPEMPLOYEEBTN1.setText("SIGN UP AS AN EMPLOYEE");
        SIGNUPEMPLOYEEBTN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SIGNUPEMPLOYEEBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGNUPEMPLOYEEBTN1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SIGNUPEMPLOYEEBTN1MouseExited(evt);
            }
        });
        jPanel5.add(SIGNUPEMPLOYEEBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 383, 530, 52));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOGUSERBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGUSERBTNMouseClicked
        new loguser().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_LOGUSERBTNMouseClicked

    private void BACKBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN1MouseClicked
      
    }//GEN-LAST:event_BACKBTN1MouseClicked

    private void SIGNUPUSERBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPUSERBTNMouseClicked
       new log().setVisible(true);
       this.dispose();
                   
    }//GEN-LAST:event_SIGNUPUSERBTNMouseClicked

    private void LOGINEMPLOYEEBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINEMPLOYEEBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINEMPLOYEEBTNMouseClicked

    private void SIGNUPEMPLOYEEBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPEMPLOYEEBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SIGNUPEMPLOYEEBTNMouseClicked

    private void BACKBTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN2MouseClicked
        System.exit(1);
    }//GEN-LAST:event_BACKBTN2MouseClicked

    private void BACKBTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN1MouseEntered
        BACKBTN1.setVisible(false);
        BACKBTN2.setVisible(true);
    }//GEN-LAST:event_BACKBTN1MouseEntered

    private void BACKBTN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKBTN2MouseExited
        BACKBTN1.setVisible(true);
        BACKBTN2.setVisible(false);
    }//GEN-LAST:event_BACKBTN2MouseExited

    private void LOGUSERBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGUSERBTN1MouseClicked
        new loguser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGUSERBTN1MouseClicked

    private void SIGNUPUSERBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPUSERBTN1MouseClicked
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SIGNUPUSERBTN1MouseClicked

    private void LOGINEMPLOYEEBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINEMPLOYEEBTN1MouseClicked
        new log().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGINEMPLOYEEBTN1MouseClicked

    private void SIGNUPEMPLOYEEBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPEMPLOYEEBTN1MouseClicked
         new sign().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SIGNUPEMPLOYEEBTN1MouseClicked

    private void LOGUSERBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGUSERBTNMouseEntered
        LOGUSERBTN1.setVisible(true);
        LOGUSERBTN.setVisible(false);     
    }//GEN-LAST:event_LOGUSERBTNMouseEntered

    private void LOGUSERBTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGUSERBTN1MouseExited
        LOGUSERBTN1.setVisible(false);
        LOGUSERBTN.setVisible(true);  
    }//GEN-LAST:event_LOGUSERBTN1MouseExited

    private void SIGNUPUSERBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPUSERBTNMouseEntered
        SIGNUPUSERBTN1.setVisible(true);
        SIGNUPUSERBTN.setVisible(false); 
    }//GEN-LAST:event_SIGNUPUSERBTNMouseEntered

    private void SIGNUPUSERBTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPUSERBTN1MouseExited
        SIGNUPUSERBTN1.setVisible(false);
        SIGNUPUSERBTN.setVisible(true); 
    }//GEN-LAST:event_SIGNUPUSERBTN1MouseExited

    private void LOGINEMPLOYEEBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINEMPLOYEEBTNMouseEntered
        LOGINEMPLOYEEBTN1.setVisible(true);
        LOGINEMPLOYEEBTN.setVisible(false); 
    }//GEN-LAST:event_LOGINEMPLOYEEBTNMouseEntered

    private void LOGINEMPLOYEEBTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINEMPLOYEEBTN1MouseExited
        LOGINEMPLOYEEBTN1.setVisible(false);
        LOGINEMPLOYEEBTN.setVisible(true); 
    }//GEN-LAST:event_LOGINEMPLOYEEBTN1MouseExited

    private void SIGNUPEMPLOYEEBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPEMPLOYEEBTNMouseEntered
        SIGNUPEMPLOYEEBTN1.setVisible(true);
        SIGNUPEMPLOYEEBTN.setVisible(false);
    }//GEN-LAST:event_SIGNUPEMPLOYEEBTNMouseEntered

    private void SIGNUPEMPLOYEEBTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUPEMPLOYEEBTN1MouseExited
        SIGNUPEMPLOYEEBTN1.setVisible(false);
        SIGNUPEMPLOYEEBTN.setVisible(true);
    }//GEN-LAST:event_SIGNUPEMPLOYEEBTN1MouseExited

    private void LOGUSERBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGUSERBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGUSERBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHOOSESERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHOOSESERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHOOSESERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHOOSESERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHOOSESERVICE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACKBTN1;
    private javax.swing.JButton BACKBTN2;
    private javax.swing.JButton LOGINEMPLOYEEBTN;
    private javax.swing.JButton LOGINEMPLOYEEBTN1;
    private javax.swing.JButton LOGUSERBTN;
    private javax.swing.JButton LOGUSERBTN1;
    private javax.swing.JButton SIGNUPEMPLOYEEBTN;
    private javax.swing.JButton SIGNUPEMPLOYEEBTN1;
    private javax.swing.JButton SIGNUPUSERBTN;
    private javax.swing.JButton SIGNUPUSERBTN1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
