/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm;

import java.sql.*;
import javax.swing.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author LENOVO
 */
public class FASTCASH extends javax.swing.JFrame {

    /**
     * Creates new form FASTCASH
     */
    public FASTCASH() {
        initComponents();
    }

    
    int MYACCNUM,qr;
    public FASTCASH (int AccNum,int n) 
    {
        initComponents();
        MYACCNUM=AccNum;
        qr=n;
        getBalance();
    }
    Connection con =null ;
    PreparedStatement pst = null;
    ResultSet Rs=null;
    int oldBalance;
    private void getBalance()
    {
            try{ 
                String query;
                if(qr==1){
                    query = "select * from employee where accnum = ? ";
                }
                else{
                    query = "select * from accounttbl where AccNum = ? ";
                }
                
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                pst.setInt(1, MYACCNUM);
                Rs = pst.executeQuery();
                if(Rs.next())
                {
                    if(qr==1){
                        oldBalance=Rs.getInt(6);
                    }
                    else{
                        oldBalance=Rs.getInt(9);
                    }
                   
                   BALLB.setText(oldBalance+".00 $");
                }
                else
                {
                    //JOptionPane.showMessageDialog(null, " Wrong Account Number Or PIN ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
    }    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EXITBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BTN50 = new javax.swing.JButton();
        BTN2000 = new javax.swing.JButton();
        BTN500 = new javax.swing.JButton();
        BTN1000 = new javax.swing.JButton();
        BTN200 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LOGOUTBTN = new javax.swing.JButton();
        BALLB = new javax.swing.JLabel();
        BTN100 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BANK OF EGYPT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 21, 790, 44));

        EXITBTN.setBackground(new java.awt.Color(102, 0, 102));
        EXITBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EXITBTN.setForeground(new java.awt.Color(255, 255, 255));
        EXITBTN.setText("X");
        EXITBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EXITBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITBTNMouseClicked(evt);
            }
        });
        jPanel2.add(EXITBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FASTCASH");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 790, -1));

        BTN50.setBackground(new java.awt.Color(102, 0, 102));
        BTN50.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTN50.setForeground(new java.awt.Color(255, 255, 255));
        BTN50.setText("50.00$");
        BTN50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN50MouseClicked(evt);
            }
        });
        jPanel1.add(BTN50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 203, 52));

        BTN2000.setBackground(new java.awt.Color(102, 0, 102));
        BTN2000.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTN2000.setForeground(new java.awt.Color(255, 255, 255));
        BTN2000.setText("2000.00$");
        BTN2000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN2000ActionPerformed(evt);
            }
        });
        jPanel1.add(BTN2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 224, 52));

        BTN500.setBackground(new java.awt.Color(102, 0, 102));
        BTN500.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTN500.setForeground(new java.awt.Color(255, 255, 255));
        BTN500.setText("500.00$");
        BTN500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN500ActionPerformed(evt);
            }
        });
        jPanel1.add(BTN500, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 224, 52));

        BTN1000.setBackground(new java.awt.Color(102, 0, 102));
        BTN1000.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTN1000.setForeground(new java.awt.Color(255, 255, 255));
        BTN1000.setText("1000.00$");
        BTN1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN1000MouseClicked(evt);
            }
        });
        jPanel1.add(BTN1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 203, 52));

        BTN200.setBackground(new java.awt.Color(102, 0, 102));
        BTN200.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTN200.setForeground(new java.awt.Color(255, 255, 255));
        BTN200.setText("200.00$");
        BTN200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN200ActionPerformed(evt);
            }
        });
        jPanel1.add(BTN200, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 203, 52));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 664, 622, -1));

        LOGOUTBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LOGOUTBTN.setForeground(new java.awt.Color(102, 0, 102));
        LOGOUTBTN.setText("LOGOUT");
        LOGOUTBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUTBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOUTBTNMouseClicked(evt);
            }
        });
        jPanel1.add(LOGOUTBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, 52));

        BALLB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BALLB.setForeground(new java.awt.Color(102, 0, 102));
        BALLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BALLB.setText("BALANCE");
        jPanel1.add(BALLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 540, 780, 44));

        BTN100.setBackground(new java.awt.Color(102, 0, 102));
        BTN100.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTN100.setForeground(new java.awt.Color(255, 255, 255));
        BTN100.setText("100.00$");
        BTN100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN100MouseClicked(evt);
            }
        });
        jPanel1.add(BTN100, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 224, 52));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BANK OF EGYPT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 790, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Desktop\\6.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 620, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN2000ActionPerformed
         if( 2000 > oldBalance )
        {   
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Amount (: ");        
        }
        else
        {
            con =null ;
            pst = null;
            Rs=null;
            String query;
            if(qr==1){
                query= "Update employee set balance = ? where accnum = ? ";
            }
            else{
                query= "Update accounttbl set Balance = ? where AccNum = ? ";
            }
            
             try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                int newBalance,row;
                newBalance = oldBalance - 2000 ;
                pst.setInt(1, newBalance );
                pst.setInt(2,MYACCNUM);
                row=pst.executeUpdate(); 
                if( row == 1)
                {
                    JOptionPane.showMessageDialog(null, " Balance Updated Successfuly (: ");
                    oldBalance=newBalance;
                    BALLB.setText(newBalance+".00 $");
                    new MainMenu(MYACCNUM,qr).setVisible(true);
                    this.dispose();
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Missing Information ): ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
        }
    }//GEN-LAST:event_BTN2000ActionPerformed

    private void BTN500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN500ActionPerformed
         if( 500 > oldBalance )
        {   
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Amount (: ");        
        }
        else
        {
            con =null ;
            pst = null;
            Rs=null;
            String query;
            if(qr==1){
                query= "Update employee set balance = ? where accnum = ? ";
            }
            else{
                query= "Update accounttbl set Balance = ? where AccNum = ? ";
            }
             try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                int newBalance,row;
                newBalance = oldBalance - 500 ;
                pst.setInt(1, newBalance );
                pst.setInt(2,MYACCNUM);
                row=pst.executeUpdate(); 
                if( row == 1)
                {
                    JOptionPane.showMessageDialog(null, " Balance Updated Successfuly (: ");
                    oldBalance=newBalance;
                    BALLB.setText(newBalance+".00 $");
                    new MainMenu(MYACCNUM,qr).setVisible(true);
                    this.dispose();
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Missing Information ): ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
        }
    }//GEN-LAST:event_BTN500ActionPerformed

    private void BTN200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN200ActionPerformed
        if( 200 > oldBalance )
        {   
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Amount (: ");        
        }
        else
        {
            con =null ;
            pst = null;
            Rs=null;
            String query;
            if(qr==1){
                query= "Update employee set balance = ? where accnum = ? ";
            }
            else{
                query= "Update accounttbl set Balance = ? where AccNum = ? ";
            }
             try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                int newBalance,row;
                newBalance = oldBalance - 200 ;
                pst.setInt(1, newBalance );
                pst.setInt(2,MYACCNUM);
                row=pst.executeUpdate(); 
                if( row == 1)
                {
                    JOptionPane.showMessageDialog(null, " Balance Updated Successfuly (: ");
                    oldBalance=newBalance;
                    BALLB.setText(newBalance+".00 $");
                    new MainMenu(MYACCNUM,qr).setVisible(true);
                    this.dispose();
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Missing Information ): ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
        }
    }//GEN-LAST:event_BTN200ActionPerformed

    private void BTN50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN50MouseClicked
        if( 50 > oldBalance )
        {   
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Amount (: ");        
        }
        else
        {
            con =null ;
            pst = null;
            Rs=null;
            String query;
            if(qr==1){
                query= "Update employee set balance = ? where accnum = ? ";
            }
            else{
                query= "Update accounttbl set Balance = ? where AccNum = ? ";
            }
             try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                int newBalance,row;
                newBalance = oldBalance - 50 ;
                pst.setInt(1, newBalance );
                pst.setInt(2,MYACCNUM);
                row=pst.executeUpdate(); 
                if( row == 1)
                {
                    JOptionPane.showMessageDialog(null, " Balance Updated Successfuly (: ");
                    oldBalance=newBalance;
                    BALLB.setText(newBalance+".00 $");
                    new MainMenu(MYACCNUM,qr).setVisible(true);
                    this.dispose();
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Missing Information ): ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
        }
    }//GEN-LAST:event_BTN50MouseClicked

    private void BTN100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN100MouseClicked
         if( 100 > oldBalance )
        {   
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Amount (: ");        
        }
        else
        {
            con =null ;
            pst = null;
            Rs=null;
            String query;
            if(qr==1){
                query= "Update employee set balance = ? where accnum = ? ";
            }
            else{
                query= "Update accounttbl set Balance = ? where AccNum = ? ";
            }
             try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                int newBalance,row;
                newBalance = oldBalance - 100 ;
                pst.setInt(1, newBalance );
                pst.setInt(2,MYACCNUM);
                row=pst.executeUpdate(); 
                if( row == 1)
                {
                    JOptionPane.showMessageDialog(null, " Balance Updated Successfuly (: ");
                    oldBalance=newBalance;
                    BALLB.setText(newBalance+".00 $");
                    new MainMenu(MYACCNUM,qr).setVisible(true);
                    this.dispose();
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Missing Information ): ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
        }
    }//GEN-LAST:event_BTN100MouseClicked

    private void BTN1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1000MouseClicked
         if( 1000 > oldBalance )
        {   
            JOptionPane.showMessageDialog(null, "Please Enter A Valid Amount (: ");        
        }
        else
        {
            con =null ;
            pst = null;
            Rs=null;
            String query;
            if(qr==1){
                query= "Update employee set balance = ? where accnum = ? ";
            }
            else{
                query= "Update accounttbl set Balance = ? where AccNum = ? ";
            }
             try{ 
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+"atmdb"+"?useUnicode=yes&characterEncoding=UTF-8", "root", "");
                pst = con.prepareStatement(query);
                int newBalance,row;
                newBalance = oldBalance - 1000 ;
                pst.setInt(1, newBalance );
                pst.setInt(2,MYACCNUM);
                row=pst.executeUpdate(); 
                if( row == 1)
                {
                    JOptionPane.showMessageDialog(null, " Balance Updated Successfuly (: ");
                    oldBalance=newBalance;
                    BALLB.setText(newBalance+".00 $");
                    new MainMenu(MYACCNUM,qr).setVisible(true);
                    this.dispose();
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "Missing Information ): ");
                }
                }
                catch (NumberFormatException | SQLException ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
        }
    }//GEN-LAST:event_BTN1000MouseClicked

    private void LOGOUTBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOUTBTNMouseClicked
        new CHOOSESERVICE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTBTNMouseClicked

    private void EXITBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITBTNMouseClicked
        System.exit(1);
    }//GEN-LAST:event_EXITBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FASTCASH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BALLB;
    private javax.swing.JButton BTN100;
    private javax.swing.JButton BTN1000;
    private javax.swing.JButton BTN200;
    private javax.swing.JButton BTN2000;
    private javax.swing.JButton BTN50;
    private javax.swing.JButton BTN500;
    private javax.swing.JButton EXITBTN;
    private javax.swing.JButton LOGOUTBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
